kind: Deployment
apiVersion: apps/v1
metadata:
  name: ansible-mcp-server
spec:
  selector:
    matchLabels:
      app: ansible-mcp-server
  replicas: 1
  template:
    metadata:
      labels:
        app: ansible-mcp-server
    spec:
      containers:
      - name: ansible-mcp-server
        image: quay.io/rcook/ansible-mcp:latest 
        ports:
          - containerPort: 8000
            protocol: TCP
          - containerPort: 8080
            protocol: TCP
        resources: {}
